
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER) VALUES (1001, 'Summer Music Festival', '2023-07-15','The Cool Cats');
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER) VALUES (1002, 'Rock Legends Live', '2023-08-20', 'The Rockin Tunes');
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER) VALUES (1003, 'Pop Hits Extravaganza', '2023-09-10','The Pop Stars');
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER) VALUES (1004, 'Jazz and Blues Night', '2023-07-30', 'The Jazz Cats');
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER) VALUES (1005, 'Country Music Showcase', '2023-10-05','The Country Crew');

INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (101, 'A1', 'Front', false, 1001);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (102, 'A2', 'Front', false, 1001);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (103, 'A3', 'Front', false, 1001);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (104, 'B1', 'Middle', false, 1001);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (105, 'B2', 'Middle', false, 1001);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (106, 'B3', 'Middle', false, 1001);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (107, 'C1', 'Rear', false, 1001);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (108, 'C2', 'Rear', false, 1001);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (109, 'C3', 'Rear', false, 1001);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (110, 'D1', 'Rear', false, 1001);

INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (201, 'A1', 'Front', false, 1002);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (202, 'A2', 'Front', false, 1002);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (203, 'A3', 'Front', false, 1002);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (204, 'B1', 'Middle', false, 1002);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (205, 'B2', 'Middle', false, 1002);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (206, 'B3', 'Middle', false, 1002);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (207, 'C1', 'Rear', false, 1002);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (208, 'C2', 'Rear', false, 1002);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (209, 'C3', 'Rear', false, 1002);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (210, 'D1', 'Rear', false, 1002);

INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (301, 'A1', 'Front', false, 1003);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (302, 'A2', 'Front', false, 1003);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (303, 'A3', 'Front', false, 1003);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (304, 'B1', 'Middle', false, 1003);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (305, 'B2', 'Middle', false, 1003);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (306, 'B3', 'Middle', false, 1003);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (307, 'C1', 'Rear', false, 1003);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (308, 'C2', 'Rear', false, 1003);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (309, 'C3', 'Rear', false, 1003);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (310, 'D1', 'Rear', false, 1003);

INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (401, 'A1', 'Front', false, 1004);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (402, 'A2', 'Front', false, 1004);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (403, 'A3', 'Front', false, 1004);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (404, 'B1', 'Middle', false, 1004);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (405, 'B2', 'Middle', false, 1004);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (406, 'B3', 'Middle', false, 1004);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (407, 'C1', 'Rear', false, 1004);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (408, 'C2', 'Rear', false, 1004);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (409, 'C3', 'Rear', false, 1004);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (410, 'D1', 'Rear', false, 1004);

INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (501, 'A1', 'Front', false, 1005);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (502, 'A2', 'Front', false, 1005);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (503, 'A3', 'Front', false, 1005);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (504, 'B1', 'Middle', false, 1005);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (505, 'B2', 'Middle', false, 1005);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (506, 'B3', 'Middle', false, 1005);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (507, 'C1', 'Rear', false, 1005);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (508, 'C2', 'Rear', false, 1005);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (509, 'C3', 'Rear', false, 1005);
INSERT INTO SEAT (ID, NUMBER, ZONE, BOOKED, CONCERT_ID) VALUES (510, 'D1', 'Rear', false, 1005);
